In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn.ensemble as sk
from sklearn.model_selection import train_test_split
from sklearn_pandas import DataFrameMapper, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
import string
import nltk
from nltk.corpus import stopwords
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import svm
import xgboost as xgb
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
df = pd.read_csv('train_file.csv')
df = df.fillna('')

In [3]:
df.head()

ID UsageClass CheckoutType  CheckoutYear  CheckoutMonth  Checkouts  \
0   1   Physical      Horizon          2005              4          1   
1   2   Physical      Horizon          2005              4          1   
2   3   Physical      Horizon          2005              4          3   
3   4   Physical      Horizon          2005              4          1   
4   5   Physical      Horizon          2005              4          1   

                                               Title               Creator  \
0                                         Tidal wave                         
1                     London holiday / Richard Peck.  Peck, Richard, 1934-   
2  Cinco de Mayo : celebrating Hispanic pride / C...      Gnojewski, Carol   
3                                          Annapolis                         
4                                  As a man thinketh                         

                                            Subjects           Publisher  \
0             Tsunamis, Tsunamis Juvenile literature                       
1                                                                Viking,   
2  Cinco de Mayo Mexican holiday History Juvenile...  Enslow Publishers,   
3  War stories, Historical fiction, Domestic fict...                       
4                               Thought and thinking                       

  PublicationYear MaterialType  
0                         BOOK  
1           1998.         BOOK  
2          c2002.         BOOK  
3                         BOOK  
4                         BOOK

In [4]:
def text_process(text):
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [5]:
x = df['Title']

In [6]:
bow_transformer = TfidfVectorizer(analyzer=text_process).fit(x)
X = bow_transformer.transform(x)

In [7]:
y = df['MaterialType']
le = LabelEncoder()
y=le.fit_transform(y)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [9]:
def fitpred(nb):
    print(nb)
    nb.fit(X_train, y_train)
    preds = nb.predict(X_test)
    mat = confusion_matrix(y_test, preds)
    print(mat)
    acc=(mat[0][0]+mat[1][1])/(mat[0][0]+mat[1][1]+mat[0][1]+mat[1][0])
    print(acc)
    print('\n')
    print(classification_report(y_test, preds))

In [11]:
nb = MultinomialNB()
fitpred(nb)
nb2 = BernoulliNB()
fitpred(nb2)
clf = svm.SVC(gamma='scale')
fitpred(clf)
clf2 = xgb.XGBClassifier()
fitpred(clf2)
clf3 = DecisionTreeClassifier()
fitpred(clf3)
clf4 = RandomForestClassifier()
fitpred(clf4)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
[[6576    0    0    0    0    3    0    0]
 [  25    0    0    0    0    0    0    0]
 [ 104    0    0    0    0    2    0    0]
 [  42    0    0    0    0   11    0    0]
 [ 323    0    0    0    0    2    0    0]
 [ 889    0    0    0    0  299    0    0]
 [ 800    0    0    0    0    3    0    0]
 [ 375    0    0    0    0    1    0   41]]
0.9962126950462051


              precision    recall  f1-score   support

           0       0.72      1.00      0.84      6579
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       106
           3       0.00      0.00      0.00        53
           4       0.00      0.00      0.00       325
           5       0.93      0.25      0.40      1188
           6       0.00      0.00      0.00       803
           7       1.00      0.10      0.18       417

   micro avg       0.73      0.73      0.73      9496
   macro avg       0.33      0.17

/home/khandalaryan/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/khandalaryan/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[6579    0    0    0    0    0    0    0]
 [  25    0    0    0    0    0    0    0]
 [ 106    0    0    0    0    0    0    0]
 [  53    0    0    0    0    0    0    0]
 [ 325    0    0    0    0    0    0    0]
 [1151    0    0    0    0   37    0    0]
 [ 803    0    0    0    0    0    0    0]
 [ 417    0    0    0    0    0    0    0]]
0.9962144155057541


              precision    recall  f1-score   support

           0       0.70      1.00      0.82      6579
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       106
           3       0.00      0.00      0.00        53
           4       0.00      0.00      0.00       325
           5       1.00      0.03      0.06      1188
           6       0.00      0.00      0.00       803
           7       0.00      0.00      0.00       417

   micro avg       0.70      0.70      0.70      9496
   macro avg       0.21      0.13      0.11      9496
weighted avg       0.61      0.70     

/home/khandalaryan/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[[5608    9    0    3   65  698  161   35]
 [  16    3    0    0    0    5    1    0]
 [  16    0   87    1    0    2    0    0]
 [   8    0    0   22    0   23    0    0]
 [ 218    1    0    0   19   63   17    7]
 [ 386    0    0    2   11  747   32   10]
 [ 478    4    1    0   22  191   87   20]
 [ 182    0    0    0    1   70   25  139]]
0.9955642299503193


              precision    recall  f1-score   support

           0       0.81      0.85      0.83      6579
           1       0.18      0.12      0.14        25
           2       0.99      0.82      0.90       106
           3       0.79      0.42      0.54        53
           4       0.16      0.06      0.09       325
           5       0.42      0.63      0.50      1188
           6       0.27      0.11      0.15       803
           7       0.66      0.33      0.44       417

   micro avg       0.71      0.71      0.71      9496
   macro avg       0.53      0.42      0.45      9496
weighted avg       0.69      0.71     

In [12]:
nbf = xgb.XGBClassifier()
nbf.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [13]:
test = pd.read_csv('test_file.csv')
test.fillna('')
X_t = test['Title']
X_t = bow_transformer.transform(X_t)
preds = nbf.predict(X_t)
preds = le.inverse_transform(preds)

In [14]:
id_ = test['ID']
label = preds
data = { 'ID': id_, 'MaterialType': label}
submission = pd.DataFrame(data)
submission.head(10)

ID MaterialType
0  31654         BOOK
1  31655         BOOK
2  31656    SOUNDDISC
3  31657         BOOK
4  31658         BOOK
5  31659         BOOK
6  31660         BOOK
7  31661         BOOK
8  31662         BOOK
9  31663         BOOK

In [15]:
submission.to_csv('submit.csv',index=False)