In [131]:
import pandas as pd
import numpy as np

In [132]:
df = pd.read_csv('train_file.csv')

In [133]:
df.head()

ID UsageClass CheckoutType  CheckoutYear  CheckoutMonth  Checkouts  \
0   1   Physical      Horizon          2005              4          1   
1   2   Physical      Horizon          2005              4          1   
2   3   Physical      Horizon          2005              4          3   
3   4   Physical      Horizon          2005              4          1   
4   5   Physical      Horizon          2005              4          1   

                                               Title               Creator  \
0                                         Tidal wave                   NaN   
1                     London holiday / Richard Peck.  Peck, Richard, 1934-   
2  Cinco de Mayo : celebrating Hispanic pride / C...      Gnojewski, Carol   
3                                          Annapolis                   NaN   
4                                  As a man thinketh                   NaN   

                                            Subjects           Publisher  \
0             Tsunamis, Tsunamis Juvenile literature                 NaN   
1                                                NaN             Viking,   
2  Cinco de Mayo Mexican holiday History Juvenile...  Enslow Publishers,   
3  War stories, Historical fiction, Domestic fict...                 NaN   
4                               Thought and thinking                 NaN   

  PublicationYear MaterialType  
0             NaN         BOOK  
1           1998.         BOOK  
2          c2002.         BOOK  
3             NaN         BOOK  
4             NaN         BOOK

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31653 entries, 0 to 31652
Data columns (total 12 columns):
ID                 31653 non-null int64
UsageClass         31653 non-null object
CheckoutType       31653 non-null object
CheckoutYear       31653 non-null int64
CheckoutMonth      31653 non-null int64
Checkouts          31653 non-null int64
Title              31653 non-null object
Creator            8516 non-null object
Subjects           29890 non-null object
Publisher          9737 non-null object
PublicationYear    9722 non-null object
MaterialType       31653 non-null object
dtypes: int64(4), object(8)
memory usage: 2.9+ MB


In [135]:
df.drop(['ID','CheckoutType','CheckoutYear','CheckoutMonth','Creator','Subjects','Publisher','PublicationYear','CheckoutType'],axis=1,inplace=True)

In [136]:
x = df['Title']

In [137]:
import string
import nltk
from nltk.corpus import stopwords
def text_process(text):
    '''
    Takes in a string of text, then performs the following:
    1. Remove all punctuation
    2. Remove all stopwords
    3. Return the cleaned text as a list of words
    '''
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [138]:
from sklearn.feature_extraction.text import TfidfVectorizer
bow_transformer = TfidfVectorizer(analyzer=text_process).fit(x)
X = bow_transformer.transform(x)

In [139]:
y = df['MaterialType']

In [140]:
X

<31653x39279 sparse matrix of type '<class 'numpy.float64'>'
	with 165155 stored elements in Compressed Sparse Row format>

In [141]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

In [142]:
y

array([0, 0, 0, ..., 7, 0, 2])

In [143]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [144]:
def fitpred(nb):
    nb.fit(X_train, y_train)
    preds = nb.predict(X_test)
    mat = confusion_matrix(y_test, preds)
    print(mat)
    acc=(mat[0][0]+mat[1][1])/(mat[0][0]+mat[1][1]+mat[0][1]+mat[1][0])
    print(acc)
    print('\n')
    print(classification_report(y_test, preds))

In [145]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn import svm
import xgboost as xgb
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report
nb = MultinomialNB()
fitpred(nb)
nb2 = BernoulliNB()
fitpred(nb2)
clf = svm.SVC(gamma='scale')
fitpred(clf)
clf2 = xgb.XGBClassifier()
fitpred(clf2)
clf3 = DecisionTreeClassifier()
fitpred(clf3)

[[6576    0    0    0    0    3    0    0]
 [  25    0    0    0    0    0    0    0]
 [ 104    0    0    0    0    2    0    0]
 [  42    0    0    0    0   11    0    0]
 [ 323    0    0    0    0    2    0    0]
 [ 889    0    0    0    0  299    0    0]
 [ 800    0    0    0    0    3    0    0]
 [ 375    0    0    0    0    1    0   41]]
0.9962126950462051


              precision    recall  f1-score   support

           0       0.72      1.00      0.84      6579
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       106
           3       0.00      0.00      0.00        53
           4       0.00      0.00      0.00       325
           5       0.93      0.25      0.40      1188
           6       0.00      0.00      0.00       803
           7       1.00      0.10      0.18       417

   micro avg       0.73      0.73      0.73      9496
   macro avg       0.33      0.17      0.18      9496
weighted avg       0.66      0.73     

/home/khandalaryan/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/khandalaryan/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[6579    0    0    0    0    0    0    0]
 [  25    0    0    0    0    0    0    0]
 [ 106    0    0    0    0    0    0    0]
 [  53    0    0    0    0    0    0    0]
 [ 325    0    0    0    0    0    0    0]
 [1151    0    0    0    0   37    0    0]
 [ 803    0    0    0    0    0    0    0]
 [ 417    0    0    0    0    0    0    0]]
0.9962144155057541


              precision    recall  f1-score   support

           0       0.70      1.00      0.82      6579
           1       0.00      0.00      0.00        25
           2       0.00      0.00      0.00       106
           3       0.00      0.00      0.00        53
           4       0.00      0.00      0.00       325
           5       1.00      0.03      0.06      1188
           6       0.00      0.00      0.00       803
           7       0.00      0.00      0.00       417

   micro avg       0.70      0.70      0.70      9496
   macro avg       0.21      0.13      0.11      9496
weighted avg       0.61      0.70     

In [146]:
nbf = xgb.XGBClassifier()
nbf.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [147]:
test = pd.read_csv('test_file.csv')

In [148]:
X_t = test['Title']
X_t = bow_transformer.transform(X_t)

In [149]:
preds = nbf.predict(X_t)

In [150]:
preds = le.inverse_transform(preds)

In [151]:
preds

array(['BOOK', 'BOOK', 'SOUNDDISC', ..., 'BOOK', 'BOOK', 'SOUNDDISC'],
      dtype=object)

In [152]:
id_ = test['ID']
label = preds
data = { 'ID': id_, 'MaterialType': label}
submission = pd.DataFrame(data)
submission.head(25)

ID MaterialType
0   31654         BOOK
1   31655         BOOK
2   31656    SOUNDDISC
3   31657         BOOK
4   31658         BOOK
5   31659         BOOK
6   31660         BOOK
7   31661         BOOK
8   31662         BOOK
9   31663         BOOK
10  31664         BOOK
11  31665         BOOK
12  31666         BOOK
13  31667         BOOK
14  31668         BOOK
15  31669         BOOK
16  31670         BOOK
17  31671         BOOK
18  31672    SOUNDDISC
19  31673         BOOK
20  31674         BOOK
21  31675         BOOK
22  31676         BOOK
23  31677         BOOK
24  31678         BOOK

In [153]:
submission.to_csv('xgb.csv',index=False)